sudo: false

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test # for gcc 4.8
          packages:
          - gcc-4.8
          - g++-4.8
      before_install:
      - export CC=gcc-4.8 CXX=g++-4.8
      install:
      # install cppcheck from source:
      - wget https://sourceforge.net/projects/cppcheck/files/cppcheck/1.69/cppcheck-1.69.tar.bz2 &&
        tar -xjf cppcheck-1.69.tar.bz2 &&
        cd cppcheck-1.69 &&
        make -j4 &&
        export PATH=$PATH:$PWD/ &&
        cd ..
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
          - llvm-3.4
          - llvm-3.4-dev
    - os: osx
      compiler: clang
      osx_image: xcode61
    # gcc would just repeat the clang test on OSX (unless we do some extra work...), so skip it
 
script:
  - mkdir build &&
    cd build &&
    ../configure --jobs=4 --prefix=../install &&
    make -j4 install &&
    ../install/bin/runMantaWorkflowDemo.py

branches:
  only:
    - master
    - travis
    - /v\d\.\d\.\d/

notifications:
  email:
    recipients:
      - csaunders@illumina.com
      - xchen@illumina.com

